name: Deploy Blog

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.USERNAME }}
      HOST: ${{ secrets.HOST }}
      CADDYFILE_PATH: /etc/caddy/Caddyfile

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploying with rsync
        run: |
          rsync -avz --delete -e "ssh -i /$HOME/.ssh/id_ed25519" $SOURCE_PATH $USERNAME@$HOST:$DEPLOY_PATH
        env:
          DEPLOY_PATH: /var/www/blog
          SOURCE_PATH: ${{ github.workspace }}/posts

      - name: Updating Caddyfile
        run: |
          scp -i ~/.ssh/id_ed25519 ./Caddyfile $USERNAME@$HOST:$CADDYFILE_PATH

      - name: Reloading Caddy
        run: |
          ssh -i ~/.ssh/id_ed25519 $USERNAME@$HOST 'caddy reload --config $CADDYFILE_PATH'
