name: Deploy Blog

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.USERNAME }}
      HOST: ${{ secrets.HOST }}
      CADDYFILE_PATH: /etc/caddy/Caddyfile

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > $SSH_PRIVATE_KEY_PATH
          chmod 600 $SSH_PRIVATE_KEY_PATH
          eval $(ssh-agent)
          ssh-add $SSH_PRIVATE_KEY_PATH
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PRIVATE_KEY_PATH: ~/.ssh/id_ed25519

      - name: Deploying with rsync
        run: |
          rsync -avz --delete ./posts $USERNAME@$HOST:$DEPLOY_PATH
        env:
          DEPLOY_PATH: /var/www/blog

      - name: Updating Caddyfile
        run: |
          scp ./Caddyfile $USERNAME@$HOST:$CADDYFILE_PATH

      - name: Reloading Caddy
        run: |
          ssh $USERNAME@$HOST 'caddy reload --config $CADDYFILE_PATH'
