name: Deploy Blog

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    env:
      USERNAME: ${{ secrets.USERNAME }}
      HOST: ${{ secrets.HOST }}
      SSH_PRIVATE_KEY_PATH: ~/.ssh/id_ed25519
      CADDYFILE_PATH: /etc/caddy/Caddyfile
      BLOG_PATH: /var/www/blog

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > $SSH_PRIVATE_KEY_PATH
          chmod 600 $SSH_PRIVATE_KEY_PATH
          eval $(ssh-agent -s) 
          ssh-add $SSH_PRIVATE_KEY_PATH
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Sync files using rsync
        run: |
          rsync -avz --delete -e "ssh -i $SSH_PRIVATE_KEY_PATH" ./posts $USERNAME@$HOST:$BLOG_PATH

      - name: Update Caddyfile
        run: |
          scp -i $SSH_PRIVATE_KEY_PATH ./Caddyfile $USERNAME@$HOST:$CADDYFILE_PATH

      - name: Reload Caddy
        run: |
          ssh -i $SSH_PRIVATE_KEY_PATH $USERNAME@$HOST 'caddy reload --config $CADDYFILE_PATH'
